// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

struct Gen_uwt_0002aaa9;
void *operator new(unsigned int, Gen_uwt_0002aaa9 *);
void operator delete(void *, Gen_uwt_0002aaa9 *);
struct Gen_uwp_0002aaa9 { int m; Gen_uwp_0002aaa9(int); };

struct Gen_uwt_00033d3e;
void *operator new(unsigned int, Gen_uwt_00033d3e *);
void operator delete(void *, Gen_uwt_00033d3e *);
struct Gen_uwp_00033d3e { int m; Gen_uwp_00033d3e(int); };

Gen_uwp_0002aaa9 *gen_uw_d8_8_0002aaa9(Gen_uwt_0002aaa9 *a0, Gen_uwt_0002aaa9 *a1) { gen_uw_sink(a0); char p[8]; gen_uw_sink(p); return new (a1) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d12_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[12]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d12_12_0002aaa9(Gen_uwt_0002aaa9 *a0, Gen_uwt_0002aaa9 *a1, Gen_uwt_0002aaa9 *a2) { gen_uw_sink(a0); gen_uw_sink(a1); char p[12]; gen_uw_sink(p); return new (a2) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d20_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[20]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d28_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[28]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d28_28_0002aaa9(Gen_uwt_0002aaa9 *a0, Gen_uwt_0002aaa9 *a1, Gen_uwt_0002aaa9 *a2, Gen_uwt_0002aaa9 *a3, Gen_uwt_0002aaa9 *a4, Gen_uwt_0002aaa9 *a5, Gen_uwt_0002aaa9 *a6) { gen_uw_sink(a0); gen_uw_sink(a1); gen_uw_sink(a2); gen_uw_sink(a3); gen_uw_sink(a4); gen_uw_sink(a5); char p[28]; gen_uw_sink(p); return new (a6) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d32_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[32]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d36_8_0002aaa9(Gen_uwt_0002aaa9 *a0, Gen_uwt_0002aaa9 *a1) { gen_uw_sink(a0); char p[36]; gen_uw_sink(p); return new (a1) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d44_8_0002aaa9(Gen_uwt_0002aaa9 *a0, Gen_uwt_0002aaa9 *a1) { gen_uw_sink(a0); char p[44]; gen_uw_sink(p); return new (a1) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d48_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[48]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_0002aaa9 *gen_uw_d92_4_0002aaa9(Gen_uwt_0002aaa9 *a0) { char p[92]; gen_uw_sink(p); return new (a0) Gen_uwp_0002aaa9(0); }

Gen_uwp_00033d3e *gen_uw_d0_8_00033d3e(Gen_uwt_00033d3e *a0, Gen_uwt_00033d3e *a1) { gen_uw_sink(a0); return new (a1) Gen_uwp_00033d3e(0); }
