// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

struct Gen_uw_0000d828 { int m; ~Gen_uw_0000d828(); };

void gen_uw_f_0000d828()
{
	Gen_uw_0000d828 v0; gen_uw_ext();
	Gen_uw_0000d828 v1; gen_uw_ext();
	Gen_uw_0000d828 v2; gen_uw_ext();
	Gen_uw_0000d828 v3; gen_uw_ext();
	Gen_uw_0000d828 v4; gen_uw_ext();
	Gen_uw_0000d828 v5; gen_uw_ext();
	Gen_uw_0000d828 v6; gen_uw_ext();
	Gen_uw_0000d828 v7; gen_uw_ext();
	Gen_uw_0000d828 v8; gen_uw_ext();
	Gen_uw_0000d828 v9; gen_uw_ext();
	Gen_uw_0000d828 v10; gen_uw_ext();
	Gen_uw_0000d828 v11; gen_uw_ext();
	Gen_uw_0000d828 v12; gen_uw_ext();
	Gen_uw_0000d828 v13; gen_uw_ext();
	Gen_uw_0000d828 v14; gen_uw_ext();
	Gen_uw_0000d828 v15; gen_uw_ext();
	Gen_uw_0000d828 v16; gen_uw_ext();
	Gen_uw_0000d828 v17; gen_uw_ext();
	Gen_uw_0000d828 v18; gen_uw_ext();
	Gen_uw_0000d828 v19; gen_uw_ext();
	Gen_uw_0000d828 v20; gen_uw_ext();
	Gen_uw_0000d828 v21; gen_uw_ext();
	Gen_uw_0000d828 v22; gen_uw_ext();
	Gen_uw_0000d828 v23; gen_uw_ext();
	Gen_uw_0000d828 v24; gen_uw_ext();
	Gen_uw_0000d828 v25; gen_uw_ext();
	Gen_uw_0000d828 v26; gen_uw_ext();
	Gen_uw_0000d828 v27; gen_uw_ext();
	Gen_uw_0000d828 v28; gen_uw_ext();
}

void gen_uw_p14_0000d828(Gen_uw_0000d828 a0, Gen_uw_0000d828 a1, Gen_uw_0000d828 a2, Gen_uw_0000d828 a3, Gen_uw_0000d828 a4, Gen_uw_0000d828 a5, Gen_uw_0000d828 a6, Gen_uw_0000d828 a7, Gen_uw_0000d828 a8, Gen_uw_0000d828 a9, Gen_uw_0000d828 a10, Gen_uw_0000d828 a11, Gen_uw_0000d828 a12, Gen_uw_0000d828 a13) { gen_uw_ext(); }
