// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

// A throwing new-expression leaves its block to be freed from a frame
// slot, and padding ahead of it walks that slot down the ladder. Slot 1
// is the exception: a 4-byte pad lands in the spare slot the frame
// already has and does not move the temporary, so only a second
// new-expression that is live at the same time reaches it.
struct Gen_uw_new { int m; Gen_uw_new(int); ~Gen_uw_new(); };
struct Gen_uw_new2 { int m; Gen_uw_new2(Gen_uw_new *); ~Gen_uw_new2(); };

Gen_uw_new *gen_uw_c0() { return new Gen_uw_new(0); }

Gen_uw_new2 *gen_uw_c1() { return new Gen_uw_new2(new Gen_uw_new(0)); }

Gen_uw_new *gen_uw_c2() { char p[8]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c3() { char p[12]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c4() { char p[16]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c5() { char p[20]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c6() { char p[24]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c7() { char p[28]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c8() { char p[32]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c9() { char p[36]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c10() { char p[40]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c11() { char p[44]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c12() { char p[48]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c13() { char p[52]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c14() { char p[56]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c15() { char p[60]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c16() { char p[64]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c17() { char p[68]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c18() { char p[72]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c19() { char p[76]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c20() { char p[80]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c21() { char p[84]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c22() { char p[88]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c23() { char p[92]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c24() { char p[96]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c28() { char p[112]; gen_uw_sink(p); return new Gen_uw_new(0); }
