// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_uw.py land
// Do not edit by hand -- regenerate. Every row in this file is anchored to a
// compiler-local $L label, so inserting or removing anything renumbers the
// labels and breaks rows whose funclet bytes never changed.
//
// Each body exists to make MSVC emit one unwind funclet that retail also emits.
// The payloads are anonymous by design -- a frame slot and a destructor call,
// never a class identity -- and every callee address is read out of the retail
// funclet and pinned in reverse/symbols.csv, so the bytes prove the target.

void gen_uw_ext();
void gen_uw_sink(void *);

// A throwing new-expression leaves its block to be freed from a frame slot,
// and padding ahead of it walks that slot down. A 4-byte pad is the
// exception: it lands in the spare slot the frame already has and does not
// move the temporary, so only a second new-expression that is live at the
// same time reaches EBP-0x14.
struct Gen_uw_new { int m; Gen_uw_new(int); ~Gen_uw_new(); };
struct Gen_uw_new2 { int m; Gen_uw_new2(Gen_uw_new *); ~Gen_uw_new2(); };

Gen_uw_new *gen_uw_c0() { return new Gen_uw_new(0); }

Gen_uw_new2 *gen_uw_c4() { return new Gen_uw_new2(new Gen_uw_new(0)); }

Gen_uw_new *gen_uw_c8() { char p[8]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c12() { char p[12]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c16() { char p[16]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c20() { char p[20]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c24() { char p[24]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c28() { char p[28]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c32() { char p[32]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c36() { char p[36]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c40() { char p[40]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c44() { char p[44]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c48() { char p[48]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c52() { char p[52]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c56() { char p[56]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c60() { char p[60]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c64() { char p[64]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c68() { char p[68]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c72() { char p[72]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c76() { char p[76]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c80() { char p[80]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c84() { char p[84]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c88() { char p[88]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c92() { char p[92]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c96() { char p[96]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c112() { char p[112]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c116() { char p[116]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c120() { char p[120]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c128() { char p[128]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c132() { char p[132]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c136() { char p[136]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c140() { char p[140]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c144() { char p[144]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c148() { char p[148]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c168() { char p[168]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c176() { char p[176]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c212() { char p[212]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c220() { char p[220]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c256() { char p[256]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c260() { char p[260]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c284() { char p[284]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c424() { char p[424]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c512() { char p[512]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c520() { char p[520]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c524() { char p[524]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c528() { char p[528]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c596() { char p[596]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c656() { char p[656]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c668() { char p[668]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c816() { char p[816]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c824() { char p[824]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c1060() { char p[1060]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c1348() { char p[1348]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c1392() { char p[1392]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c2120() { char p[2120]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c2124() { char p[2124]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c2248() { char p[2248]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c2256() { char p[2256]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c3096() { char p[3096]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c3356() { char p[3356]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c4140() { char p[4140]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c4156() { char p[4156]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c4164() { char p[4164]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c4240() { char p[4240]; gen_uw_sink(p); return new Gen_uw_new(0); }

Gen_uw_new *gen_uw_c5416() { char p[5416]; gen_uw_sink(p); return new Gen_uw_new(0); }
