// cl: /DNDEBUG /DWIN32 /D_WINDOWS /MD /EHsc /Ireference/shims/sweep /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Source /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/Compression /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/debug /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngineDevice/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Main /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWLib /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2 /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWMath /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWSaveLoad /D_STLP_USE_STATIC_LIB
// stlport
// Generated by: the phase-5 census-family instantiation spike.
// Do not edit by hand.
//
// Each row here is a retail STLport body the census found unclaimed and whose
// shape a matched game-source row already carries -- that twin names the
// instantiation, and the instantiation is re-stated below so the compiler emits
// the same COMDAT. Every byte outside the relocation slots was compared against
// the live retail body before the row was written, and every call in it resolves
// to the address retail encodes.

#include "PreRTS.h"
#include "Common/STLTypedefs.h"
#include "Common/ThingTemplate.h"

#include <map>
#include <set>
#include <list>

// f629_f3736f / f183_a25a66: the twin symbols spell map<AsciiString, list<AsciiString> >.
template class _STL::map<AsciiString, _STL::list<AsciiString> >;
// f145_000172: _Rb_tree<int, pair<const int, unsigned int> >
template class _STL::map<Int, UnsignedInt>;
// f145_7c76b9: _Rb_tree<unsigned int, pair<const unsigned int, State *> >
class State;
template class _STL::map<UnsignedInt, State *>;
// f176_e217c9: _Rb_tree<const ThingTemplate *, const ThingTemplate *, _Identity>
template class _STL::set<const ThingTemplate *>;
