// cl: /DNDEBUG /DWIN32 /D_WINDOWS /MD /EHsc /Ireference/shims/sweep /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Source /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/Compression /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/debug /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngineDevice/Include /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Main /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWLib /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2 /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWMath /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug /Ireference/CnC_Generals_Zero_Hour/GeneralsMD/Code/Libraries/Source/WWVegas/WWSaveLoad /D_STLP_USE_STATIC_LIB
// stlport
// Generated by: the phase-5 ZH STLport instantiation spike.
// Do not edit by hand.
//
// Every row this file carries is a retail body the ZH sources compile to. The
// game links STLport 4.5.3, so a container member is the vendor template over
// a game type, and the harvest of the EA reference sources named the exact
// instantiation at each address. Those instantiations are re-stated here so
// the compiler emits the same COMDATs, and each row's `object-symbol=` points
// at the one whose bytes build.py compares against retail.
//
// The flags matter as much as the code: retail linked the STLport static
// library, so /D_STLP_USE_STATIC_LIB is what keeps __new_alloc::allocate a
// direct call instead of a call through the import table, and /MD is what
// makes memmove a six-byte call through the import table.

#include "PreRTS.h"
#include "Common/STLTypedefs.h"
#include "Common/AudioEventRTS.h"
#include "Common/AudioRequest.h"
#include "Common/ArchiveFile.h"
#include "Common/ArchiveFileSystem.h"

#include <hash_map>
#include <list>
#include <map>
#include <set>
#include <vector>

// list<T> instantiates remove()/unique()/sort() whether or not the game calls
// them, so payloads without these operators only need them declared.
bool operator==(const Coord3D &, const Coord3D &);
bool operator<(const Coord3D &, const Coord3D &);

template class _STL::hash_map<AsciiString, AudioEventInfo *, rts::hash<AsciiString>, rts::equal_to<AsciiString> >;
template class _STL::list<AudioRequest *>;
template class _STL::list<_STL::pair<AsciiString, Real> >;
template class _STL::list<Coord3D>;
template class _STL::set<AsciiString, rts::less_than_nocase<AsciiString> >;
template class _STL::set<AsciiString>;
template class _STL::map<AsciiString, Coord3D>;
template class _STL::map<AsciiString, ArchivedFileInfo>;
template class _STL::map<AsciiString, DetailedArchivedDirectoryInfo>;
