// cl: /DNDEBUG /MD /EHsc

class GeometryUpgradeModuleData
{
public:
    GeometryUpgradeModuleData();
};

__declspec(naked) GeometryUpgradeModuleData::GeometryUpgradeModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 98h
        _emit 49h
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 8Dh
        _emit 4Eh
        _emit 08h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 0E8h
        _emit 9Fh
        _emit 93h
        _emit 0D3h
        _emit 0FFh
        _emit 33h
        _emit 0C0h
        _emit 0C7h
        _emit 06h
        _emit 90h
        _emit 0CDh
        _emit 0Ch
        _emit 01h
        _emit 89h
        _emit 46h
        _emit 70h
        _emit 89h
        _emit 46h
        _emit 74h
        _emit 89h
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 89h
        _emit 46h
        _emit 78h
        _emit 89h
        _emit 46h
        _emit 7Ch
        _emit 89h
        _emit 86h
        _emit 80h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 86h
        _emit 84h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 8Dh
        _emit 8Eh
        _emit 88h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 01h
        _emit 8Dh
        _emit 0BEh
        _emit 8Ch
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 07h
        _emit 8Dh
        _emit 9Eh
        _emit 90h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 03h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 05h
        _emit 0E8h
        _emit 0F3h
        _emit 1Bh
        _emit 5Bh
        _emit 00h
        _emit 8Bh
        _emit 0CFh
        _emit 0E8h
        _emit 0ECh
        _emit 1Bh
        _emit 5Bh
        _emit 00h
        _emit 8Bh
        _emit 0CBh
        _emit 0E8h
        _emit 0E5h
        _emit 1Bh
        _emit 5Bh
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 10h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}
