#!/usr/bin/env python3
"""Claim unclaimed retail functions as byte-true naked dumps, in waves.

The split this enables: everything deterministic is scripted, and agents spend
themselves only on the one step that cannot be scripted — turning ASM into
byte-exact C++. A dump IS the retail bytes, so it verifies by construction,
claims the body in the ledger, pins its boundary, and lands in
list_naked_candidates' convert queue automatically. Converting it later is the
established repoint flow (same range, clean C++ replaces the dump).

Waves are deliberate, not exhaustive. Serving 43k anonymous bodies at once
would swamp the convert lane with work nobody can identify; a wave takes the
highest-expected-yield slice (measured land rates peak at 128-255B) and
anything carrying an identity lead in reverse/anchored_candidates.csv, so the
queue stays fuel rather than landfill. Gate further waves on the measured
convert rate of the previous one.

Each wave writes Code/gen_small/dumps_<NNN>.cpp plus its ledger rows
(`d_<rva>` free functions, notes `gen-dump;ghidra=<name>`), then byte-verify:

  python3 tools/gen_dump.py --wave 0 --limit 400
  ./build.sh Code/gen_small/dumps_000.cpp
"""
import argparse
import bisect
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build
import progress
import yield_model

ROOT = Path(__file__).resolve().parents[1]
GHIDRA = ROOT / "reverse" / "ghidra_functions.csv"
ANCHORED = ROOT / "reverse" / "anchored_candidates.csv"
FUNCTIONS = ROOT / "reverse" / "functions.csv"

HEADER = """\
// cl: /DNDEBUG /MD /EHsc
// Generated by: python3 tools/gen_dump.py --wave {wave} --limit {limit}
// Do not edit by hand; convert bodies to clean C++ and repoint instead.
//
// Each d_<rva> reproduces the retail bytes of the unclaimed function at that
// RVA — byte-true by construction, semantically anonymous. These exist to be
// REPLACED: list_naked_candidates.py serves them to the convert lane, and a
// clean C++ body lands over the same range with add_match --replace-existing.
"""

BODY = """\

// ghidra: {ghidra}{lead}
__declspec(naked) void d_{rva:08x}()
{{
    __asm {{
{emits}
    }}
}}
"""


def ledger_ranges():
    """Sorted claimed [start, end) ranges straight from the ledger."""
    ranges = []
    with FUNCTIONS.open(newline="") as handle:
        for row in csv.DictReader(handle):
            if row["target_rva"] and row["target_size"]:
                start = int(row["target_rva"], 16)
                ranges.append((start, start + int(row["target_size"])))
    ranges.sort()
    return ranges


def overlaps(ranges, starts, lo, hi):
    index = bisect.bisect_left(starts, hi)
    return index > 0 and ranges[index - 1][1] > lo


def candidates(args):
    text = next(s for s in build.pe_sections(build.EXE.read_bytes())
                if s["name"] == ".text")
    text_lo, text_hi = text["rva"], text["rva"] + text["size"]
    ranges = ledger_ranges()
    starts = [start for start, _ in ranges]
    anchored = set()
    if ANCHORED.exists():
        with ANCHORED.open(newline="") as handle:
            anchored = {int(r["target_rva"], 16) for r in csv.DictReader(handle)}
    out = []
    with GHIDRA.open(newline="") as handle:
        for row in csv.DictReader(handle):
            rva, size = int(row["rva"], 16), int(row["size"])
            if not (args.min_size <= size <= args.max_size):
                continue
            if rva < text_lo or rva + size > text_hi:
                continue
            # Strict zero overlap: a dump inside anyone's range is an over-claim.
            if overlaps(ranges, starts, rva, rva + size):
                continue
            out.append((rva, size, row["name"], rva in anchored))
    # Identity leads first, then measured expected yield, then address for
    # determinism — same wave inputs always produce the same wave.
    out.sort(key=lambda c: (not c[3], -yield_model.land_rate(c[1]) * c[1], c[0]))
    return out


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--wave", type=int, required=True)
    parser.add_argument("--limit", type=int, default=400)
    parser.add_argument("--min-size", type=int, default=96)
    parser.add_argument("--max-size", type=int, default=511)
    args = parser.parse_args()

    source = ROOT / "Code" / "gen_small" / f"dumps_{args.wave:03d}.cpp"
    if source.exists():
        raise SystemExit(f"{source.relative_to(ROOT)} already exists — waves are "
                         f"append-only; use the next --wave number")

    exe = build.EXE.read_bytes()
    text = next(s for s in build.pe_sections(exe) if s["name"] == ".text")
    picked = candidates(args)[:args.limit]
    if not picked:
        raise SystemExit("no eligible unclaimed functions in this band")

    pieces = [HEADER.format(wave=args.wave, limit=args.limit)]
    rows = []
    for rva, size, ghidra_name, is_anchored in picked:
        offset = text["raw_pointer"] + (rva - text["rva"])
        body = exe[offset:offset + size]
        emits = "\n".join(f"        __emit 0x{byte:02x}" for byte in body)
        lead = "  (identity lead in reverse/anchored_candidates.csv)" if is_anchored else ""
        pieces.append(BODY.format(ghidra=ghidra_name, lead=lead, rva=rva, emits=emits))
        rows.append((f"?d_{rva:08x}@@YAXXZ", rva, size,
                     f"gen-dump;ghidra={ghidra_name}"))

    source.write_text("".join(pieces), newline="\n")
    rel = source.relative_to(ROOT).as_posix()
    with FUNCTIONS.open("ab") as handle:   # binary append, CRLF, like add_match
        for name, rva, size, notes in rows:
            handle.write(f"{name},,0x{rva:08X},{size},{rel},matched,{notes}\r\n"
                         .encode("ascii"))

    total = sum(size for _, _, size, _ in rows)
    anchored_count = sum(1 for *_, is_anchored in picked if is_anchored)
    print(f"wave {args.wave:03d}: {len(rows)} dumps, {total:,} bytes "
          f"({anchored_count} with identity leads) -> {rel}")
    print(f"verify: ./build.sh {rel}")


if __name__ == "__main__":
    main()
